### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/plugin.video.watchnixtoons2#11]
Hey doko,
A brief explanation of what changes were made from one version to the next would be nice.

Have a good one.

**Comment by doko-desuka** [comment]
Hi bjgood,  
I try to do that in the "news", which is what you see when you go to the add-on config screen (not the settings, but the screen where you can uninstall it or force-update it).

See here:  
https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/addon.xml#L14

**Comment by mrferdinand** [comment]
Doko,

No issues on my end. Just wanted to thank you for providing this. I've been trying to find a substitute for a number of months when the first nixtoons went down so thank you for this. For real.

**Comment by doko-desuka** [comment]
Hi @mrferdinand, I'm glad it's working for you. The source website is great.

**Comment by bjgood** [comment]
Hey Doko,
"Play Chapters", in the context menu, only shows up if "Clean Episode Titles" is unchecked. Also, if "Clean Episode Titles" is checked the dialog box does not pop up when you click on a multi-chapter episode (it only plays the first chapter of a multi-chapter episode). Of course with reference  to SpongeBob. Any of the first episodes will show you what I'm talking about. Good attempt at it, though. Like I've said before, you're a great coder, doko.

**Comment by doko-desuka** [comment]
I forgot to add the context menu setup to the clean name function, I'll add it soon.

**Comment by doko-desuka** [comment]
@bjgood ok, if the clean titles option is working with the context menu now, please close.

**Comment by doko-desuka** [comment]
Hi @bjgood, the problem is that things are so disorganized over at the source website (usually on older shows), there's no good way to determine when a page has two video players that actually point to different content (different videos), or if they're just mirrors for the same episode.  
Since it's rare to have shows where WCO separates into two different videos (for instance, Star vs. the Forces of Evil has the two chapters in the same video, instead of split), I think the context menu is the less intrusive choice: people only need to use it when necessary.  
The only other report I got about this split episode thing was someone on Reddit asking about Archer, another show on WCO which also splits the episodes in two. So luckily it's pretty rare.

**Comment by doko-desuka** [comment]
If it ends up being too annoying to use the context menu for you, it's fortunately simple to hack it to always show you the dialog, it's this IF condition here:
https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/fd5c32143c763fa6885a882e58e8b0503b1c51a6/Lib/Plugin.py#L966

You want to remove the `'playChapters' in params and` part so that only the `content.find(...)` and the rest of the line remains, meaning it will always try to parse the multiple video players even if you didn't ask it (caused by the 'playChapters' parameter).

**Comment by bjgood** [comment]
Hi Doko,
I'm aware of the context menu option for Play Chapters, so it will not be a problem for me. It's other people that I was concerned about. If they don't know about the series having separate video chapters they'll be left wondering. And, you're right, it is a rare occurrence when this happens. I just think that when multi-part episodes do occur the dialog box should pop up...like in 0.2.8.

You're a great and creative coder, doko, but for the life of me, I don't know why you added that context menu feature. IMO, it wasn't needed. It just complicates matters.

Have a good one, bud.
