### ISSUE TITLE
Watchnixtoons2

### ISSUE THREAD

**Issue by Cheshur** [doko-desuka/plugin.video.watchnixtoons2#27]
I haven't used this before but it was already installed onto my firestick in kodi. I tried three different anime and the quality options came up but after clicking on either of the quality options nothing would happen. I went to update but it said update failed. I tried uninstalling and reinstalling but it said installation failed. I went to redo everything over by adding the file source but it would say its unable to connect.

**Comment by doko-desuka** [comment]
Sounds like a faulty installation. If you don't have the latest version of the add-on then I don't guarantee it working well, because the website changes from time to time.  
An older version will not work.  

Here's what I tested:
- Uninstalled WNT2.
- Added `https://doko-desuka.github.io` (note the hyphen in the name) as a source in Settings > File Manager, giving it some name.
- Went to Add-ons > add-ons browser (the little open box icon) > Install from Zip file > chose that name that I added > installed `doko.repository-0.1.0.zip`
- Went to Install from Repository, chose doko repository, Watchnixtoons2. Installation went fine.
- Browsed for some movie, it played (didn't let pick a quality since there was only one quality). Browsed for some anime (this time it did have different qualities so the dialog appear), and it played fine.

So I'm confirming it's working. Please check your end.
