### ISSUE TITLE
For multipart episodes, like "42-43" not working in makeListItemClean

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/plugin.video.watchnixtoons2#3]
Hey doko,
The "For multipart episodes, like "42-43" is not working in function makeListItemClean. Examples...Adventure Time Season 5 Episode 50-51, Season 6 Episode 1-2, and others. Works fine for non-multipart episodes.

Works in makeListItem mode.

Have a good day, doko. :).

**Comment by doko-desuka** [comment]
Hi bjgood, thanks for the report, will take a look.

**Comment by doko-desuka** [comment]
Okay, it should work better now. Let me upload the files.

In some cases they use inconsistent formatting (like "Adventure Time Season 10 Episode 13 - 16", with spaces).  
I don't think it's worth trying to fix for every possible variation, because these title functions get called for every single list item so they must be kept efficient.

**Comment by bjgood** [comment]
Thanks, for the fix, doko.

I've made the break and replaced WatchNixtoons with WatchNixtoons2. What I've noticed, which actually surprised me, is the speed difference. From loading a series to unchecking a watched episode...it seems noticeably quicker.
