### ISSUE TITLE
Some titles work on the site not on the addon

### ISSUE THREAD

**Issue by Cryptonite26** [doko-desuka/plugin.video.watchnixtoons2#31]
Hey man, I thank you for your amazing work getting my favourite anime site a Kodi addon, I have an issue though, I am binge watching diamond no ace and when I got the season 2 (not act 2) Kodi kept giving me an error. Trying to play previous episodes works fine, it's only the transition to the new season that spazes out.

I checked their site and it works 100% there. I also tried D.C.II S.S Da capo Second season English subbed (random anime in the D list under subbed anime) and experience the same issue, tried the original (top anime in D list) and it works fine. idk what the issue might be.

Sorry for the trouble. I understand if it's not something you're going to fix soon but I thought it worth a try since I prefer your addon above all the others.

**Comment by doko-desuka** [comment]
Hi @Cryptonite26, thanks for the report.  
This was happening because the code was expecting a certain episode title format (`"[Show Name] Season [Season Number] Episode [Episode Number] [Optional Episode Title]"`), and your Diamond No Ace Subbed English used a different title format.  
I added some fallbacks for when this happens, so it should always play even if it can't identify what season an episode belongs to.  

If you find some other episodes that fail then report back.

**Comment by Cryptonite26** [comment]
Thank you for the amazingly fast response and fix. everything is working as it should now, will report any other issues I come across. I really appreciate your work.
