### ISSUE TITLE
invisible names for some shows

### ISSUE THREAD

**Issue by FiFeX** [doko-desuka/plugin.video.watchnixtoons2#36]
As you can see [here](http://prntscr.com/r6m5ro), some shows (but not all of them) got invisible names.

**Comment by doko-desuka** [comment]
Starting from the add-on main menu, what steps did you do to reach that screen?

**Comment by doko-desuka** [comment]
(Thanks for the report by the way.)

**Comment by FiFeX** [comment]
> 
> 
> Starting from the add-on main menu, what steps did you do to reach that screen?

Went to search and searched "Monster",but it happens at any search (of course).

**Comment by Cryptonite26** [comment]
I can confirm this is also happening to me, but it seems the invisibly named anime are repeats of those with actual names so it's not a major deal.

side question, why was toonmania2 pulled from your repository? sorry for the offtopic, I was just curious since it worked about 2 months ago still on my girlfriends little brother's kodi and I just now found out it was also your addon when I was searching for an updated version. (he likes the fact that he could see thumbnails) 

I'm just curious what happened. not asking you to reboot it or anything since I know you hardly have time for nixtoons.

**Comment by doko-desuka** [comment]
Okay, found the issue, very simple fix. Update submitted.

@Cryptonite26 Toonmania2 was OK while it lasted. I had decompiled the APK for their Android app and saw the web api routes that they used, making the Kodi add-on call those. So no website scraping needed, it was getting data straight from the source and was a bit faster and lighter for that.  
They had great thumbnails, but the video quality was terrible. Biggest resolution was about 360p I think.

I went to check on Toonmania2 a few months ago since someone said it wasn't working anymore, and found that the web api used by their app wasn't working anymore, so it'd have to scrape their websites (like WNT2 does with its source). I didn't have time to do that so I decided to drop it.

**Comment by doko-desuka** [comment]
Their apps are in this link, I don't think they work anymore: https://tinyurl.com/hwg4r8r

**Comment by Cryptonite26** [comment]
the app seems to work, but it looks like you're only able to watch subbed anime now so that sucks.

anyway like I said it's for someone else. I'm very satisfied with nixtoons. Thank you for all your efforts.

**Comment by Cryptonite26** [comment]
oh wait it seems if you click an episode you can choose dubbed. still though the site seems very mediocre.

**Comment by doko-desuka** [comment]
If that someone else is using an Android TV box then it should work with these toonmania / animania apps.

**Comment by Cryptonite26** [comment]
yeah, no it's a windows pc they just use Kodi for the controller support and keeping track of what's been watched. no need to stress. they got a liking to nixtoons now 🍡
