### ISSUE TITLE
Nixtoons 2 paid accounts only?

### ISSUE THREAD

**Issue by ebenjames** [doko-desuka/plugin.video.watchnixtoons2#39]
My nixtoons 2 says no free watching only paid accounts will work. If that’s the case where do I sign up?

**Comment by doko-desuka** [comment]
That's right, I added that notice just now.
Now that you asked, I haven't looked into "paid account" support. I don't know how it works.

The main registration page seems to be this: https://user.wco.tv/wp-login.php?action=register

**Comment by doko-desuka** [comment]
The problem with letting people use paid accounts is that there's a security problem with them having to input the password into the add-on settings, so the add-on will be able to see the passwords (meaning, the user will have to trust me, a strange person, that their password is going to stay protected).

**Comment by Cryptonite26** [comment]
wait what's this all about? I don't have any paid account issues?

**Comment by skechy012** [comment]
I'm assuming that the paid account content is causing some of the shows to give a playback error. I checked world trigger on their site and it seems like it's now considered premium content that needs a login so I guess that's causing errors?

**Comment by ShakarSaleem** [comment]
Hi I've just saw the message when I tried to open watchnixtoons 2. This is very disappointing,is nothing that can be done, or do we have to play the long waiting game.

**Comment by bjgood** [comment]
Hey doko,
As of 4:45pm EDT WatchNixtoons2 is back to normal. The website is not asking you to register to watch cartoons. Don't know how long it will last, though. BTW, m.watchcartoononline.io was working earlier in the day while thewatchcartoononline.tv and wcostream.com were wanting you to register.

**Comment by mrferdinand** [comment]
Appreciate the update

**Comment by minkfink** [comment]
Hey there, went on the website now no signs of paid for registration. Even the link you provided to register says “user registration is currently not allowed” 

Tried to view a few episodes and a couple of movies and all worked without issues. 

Surely all is back to normal?

**Comment by bonn2** [comment]
I just reverted to 0.4.3 and spongebob loaded and played just fine. So for now if you really want to watch something that is an option. Hopefully the repo updates tho so everyone can get back on

**Comment by doko-desuka** [comment]
Hi everyone,

> As of 4:45pm EDT WatchNixtoons2 is back to normal. The website is not asking you to register to watch cartoons. Don't know how long it will last, though.

@bjgood it does seem that way, thanks for the notice. I've submitted v0.4.6 which takes away the paywall notification, so hopefully things should be working again.  

Please note that I removed the "autoplay highest quality" setting, so now you're always asked what quality to play (though you can always select the highest one anyway, making no difference). Maybe this way more people end up using the perfectly-watchable 480p streams instead of the heavier 720p.

I'll keep this issue open in case the circumstances change.

**Comment by Cryptonite26** [comment]
so I'm still gonna use 0.4.3 since I really want the play lowest quality function so that when I click next I don't have to bother with the quality dialog popping up every time. I always watch 480p streams

**Comment by doko-desuka** [comment]
Hmm, allowing only autoplay on the lower setting would be better, indeed, more convenient.
Anyway, it's a single click (since the 480p already comes preselected in the dialog), it takes way more for it to load than for the user to click, so in a future update we can restore that setting...

**Comment by ShakarSaleem** [comment]
Hi guys I may have to wait a bit longer. But the update still has not come through and the message still pops up when clicking on the add-on.

**Comment by ShakarSaleem** [comment]
Is anyone else experiencing this too.

**Comment by bjgood** [comment]
Just a guess on my part, but this brief change on the part of the website could a signal from them that they need money. I suggest that we spread the word to contribute to their website. They're probably getting hammered by WatchNixtoons2 since it's so popular. A small price to pay to keep the site up and running as normal. It is the best cartoon website on the internet, you know.

And, doko, I'd restore the default quality to SD (like before). Everybody hates popups. A lot of kids are controlling the remote during cartoon time. Let's make it easy for them. 

Later, bud.

**Comment by Cryptonite26** [comment]
> Hmm, allowing only autoplay on the lower setting would be better, indeed, more convenient.
> Anyway, it's a single click (since the 480p already comes preselected in the dialog), it takes way more for it to load than for the user to click, so in a future update we can restore that setting...

yeah I use autoload next episode while lying in bed using it on a desktop pc usually it's not that big of a deal except when I'm bingewatching it causes the delay between episodes to be more haha nitpicking on my part but using 0.4.3 is fine.

**Comment by terrormaniac22** [comment]
Just update with te zip you can download i had the same problem now on 0.4.6 i have no problem

**Comment by Rhysowen83** [comment]
Hi, fairly new here and desperately trying to get it working again! 

Can I just check what people mean when they say version 0.4.3 or 6- is that the zip for the repo? I’m currently on 0.1.0 so do I need to download a newer one? Any help would be greatly appreciated thanks guys!

**Comment by rojasj1** [comment]
So how should address this issue should we uninstall and re-install for this to clear out? Downgrade to the previous version? Or register for the premium. Because for some odd reason it works completely fine on my phone I can watch my anime just fine but when I try to use it on my firestick it shows as the source website is temporarily blocked

**Comment by Rhysowen83** [comment]
I figured it out mate, click on recently updated in kodi, hit options on doko and check for updates, it will auto update nixtoons properly 👍🏻

**Comment by doko-desuka** [comment]
>So how should address this issue should we uninstall and re-install for this to clear out?

You need to update to the latest version, which at this moment is 0.4.6.  

Because of an annoying Kodi behavior, if Kodi shows version "0.4.5" you in your updates list, then you'll need to go find Doko Repository and long-press / right-click on it, and choose "Check for updates" so that it will refresh Doko Repository and find that there's a 0.4.6 available, and forget about that 0.4.5.

**Comment by doko-desuka** [comment]
> And, doko, I'd restore the default quality to SD (like before). Everybody hates popups. A lot of kids are controlling the remote during cartoon time. Let's make it easy for them.

@bjgood after sleeping on it I have a stronger stance. It is supposed to be inconvenient like this, to add a small (really, almost negligible) pause, as a reminder that it's not for granted, we are freeloading their videos and server bandwidth, if everyone goes at it with thrist they might pull the plug again.
