### ISSUE TITLE
Watch Nixtoons2 Paying ?

### ISSUE THREAD

**Issue by LordRamio** [doko-desuka/plugin.video.watchnixtoons2#41]
Until mid March I could watch animes freely on nixtoons2
now I get a message that it's only playing for paying customers but I am trying to understand why paying for now and to find where is that paying site.

Thanks

**Comment by doko-desuka** [comment]
Hi @LordRamio, that was from when the source website started blocking all free views. This probably happened because tons of people were accessing it (from everyone being quarantined, internet usage increased).  

But that block has since been removed. You must be using an old add-on version.  

On WatchNixtoons2 version 0.4.6 and up the views are back to normal. Please get this update when you can.

**Comment by LordRamio** [comment]
I`ll check tonight on updating the version and keep you posted.  
Thanks

**Comment by doko-desuka** [comment]
Okay, I'm gonna close this Issue but we can still comment on it, if necessary.

**Comment by LordRamio** [comment]
Updated it on one of My boxes, it works fine, Thanks again. !!  :D
