### ISSUE TITLE
Nixtoon down?

### ISSUE THREAD

**Issue by rcjrulz** [doko-desuka/plugin.video.watchnixtoons2#44]
Cant seem to get videos to load on kodi. The website also seems to be down.
Any info?

**Comment by Kaingmbl** [comment]
Every time I pick an episode it says there's an error. So mines not working either

**Comment by legrandlolo** [comment]
I'm trying to watch Inuyasha. It was working well yesterday. Now it keeps saying error too.

**Comment by doko-desuka** [comment]
I tried playing some Latest Releases items and they worked.  
Sometimes a show works while others don't, so you need to say exactly what show and episode you're trying to watch so that others can test on their end.

If you can't access the source website ([see the address on this line](https://github.com/doko-desuka/plugin.video.watchnixtoons2/blob/master/Lib/Plugin.py#L30)) using a web browser, then you've probably been geoblocked, and if that's the case, there'd be nothing we could do from the add-on other than adding support for proxy settings (you subscribe to a service like NordVPN to get a private proxy, with login and password, that the add-on can use to stream videos).

**Comment by doko-desuka** [comment]
(For instance, the show, episode and if it's the dubbed or subbed version that's not working. If someone else can test and see that it's working then that rules out the most obvious problems like a simple website update.)

**Comment by rcjrulz** [comment]
Well I did try through vpn, still wont load through Kodi. On the other hand, the website now loads properly.

**Comment by Kaingmbl** [comment]
I just tried using a vpn on kodi it still doesn't work. Certain shows will work but no movies.

**Comment by doko-desuka** [comment]
> Certain shows will work but no movies.

Can you tell me one or two movies that won't work?

**Comment by Kaingmbl** [comment]
I tried some of the Dragon Ball movies and they just wouldnt work I even tried using URL Resolver but it did nothing.

**Comment by Kaingmbl** [comment]
The movies by title are Dragon Ball Z Coolers Revenge and Dragon Ball Super Broly.

**Comment by doko-desuka** [comment]
If you go to the website and try to watch DB Super Broly Dubbed, the video player has this warning:  

![wnt2 paywall](https://user-images.githubusercontent.com/31810999/79680988-20c0e980-81ec-11ea-9f79-ee8a57cc838e.png)

This is the paywall warning from a few weeks ago. There's nothing to do from the client-side to remove that.  
I suggest trying a different add-on (like [WSBeta](https://github.com/doko-desuka/plugin.video.wsbeta), Hummingbird, WonderfulSubs etc.).

**Comment by rcjrulz** [comment]
Is there any addon that shows cartoons, not anime, like the old time xmen, batman etc?

**Comment by bjgood** [comment]
> Is there any addon that shows cartoons, not anime, like the old time xmen, batman etc?

I'd like to know an answer to that question, too. Obviously this is going to be an reoccurring problem with WCO.

Hey, doko.

**Comment by doko-desuka** [comment]
@rcjrulz @bjgood like the good old days of Exodus forks, we need to find scrapeable sites with cartoon shows, in order to write Kodi video add-ons that scrape those websites for streamable videos.  
It's alright if the site uses video player embeds from external sources, as long as those sources themselves are also scrapeable (which is what ResolveURL does, it's a scraper library specialized in video hoster sites).
