### ISSUE TITLE
Take a look at this...

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/plugin.video.watchnixtoons2#9]
Hey doko,
Take a look at SpongeBob 9x23a. You'll notice that instead of tabs at the top with Player 1, Player 2, etc. (with each chapter in them), in 9x23a there are two distinct players with different chapters in each. WatchNixtoons 2 doesn't catch this difference in page structure, and, as a result, only plays the first chapter while skipping the second.

This issue is not a biggie by any means, doko. We're only talking one video chapter here. But, there might be other series within WCO with this structure. I seem to recall seeing this layout before, but I can't remember the name of the series. I've been using WCO addons since spoyser developed it (followed by dandy...btw, your dialog approach reminds me of how he handled it).

Also, it would be nice if you could change the code to take into consideration episodes with alphabet characters in the title (like 11x17b or 12x02A) instead of just digits. Again, not a biggie.

You would know better than anyone, but is it possible to play one chapter after another in an episode rather than bringing up a dialog box?

Thanks, doko.

**Comment by doko-desuka** [comment]
Okay, it shouldn't fail now at recognizing the chapters, but the chapter names on the selection dialog were downgraded to generic "Chapter 1, 2 3" etc. because there's too many variations (Archer is another cartoon with multiple chapters, different layouts), it's not worth the time.  

As for the chapter queueing (automatically playing several chapters, one after the other), and the episode title letters, I don't have time right now to go through those, unfortunately. If you find someone that can help with that, I can review their submitted code.

**Comment by bjgood** [comment]
Thanks, doko, for the reply.

Have a good one.

**Comment by bjgood** [comment]
I see you fixed the missing chapter problem. Thanks.

I changed line 951 from this...

'Select Chapter', ['Chapter '+str(n) for n in xrange(1, len(dataIndices)+1)]

to this...

'Select Episode Chapter', ['Chapter '+str(n) for n in xrange(1, len(dataIndices)+1)]

to make it a little more succinct.

Nice work, doko. :).

It's a shame you dropped placing the chapter title in the selection dialog box, though, for it made everything more clear. But, I suppose, you had to from a coding perspective.

Thanks, again.

**Comment by doko-desuka** [comment]
I think the right name would be "Choose video player", because on some shows (like that Archer one), there are two players on the page, but both are for the same video. They just use different sources.

I was using the presence/absence of titles to tell when the page has different chapters and when it's just mirror players, but then there's that 9x23a episode (which you luckily found) that fails that criterion. So, just show everything to the user, let them decide what to do.

**Comment by doko-desuka** [comment]
But I liked the chapter titles too.

**Comment by bjgood** [comment]
IMO, you should go back to 0.2.7. It's not worth the trouble for such a rare occurrence in an episode screw up. I like the title being in the dialog box better than the current version. WCO (the site), obviously, is not consistent in it's handling of an episode layout. They're all over the place. You can't code for every strange variation that arises.

It's your creation, doko, but I vote to go back.
